services:
  - type: web
    name: rtvts-api
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        value: postgresql://trackpoint_postgresql_user:4VArxFEh2BanA5EP1qRpp5drCnPWvXsM@dpg-da5fegqjobas73ehvi10-a.singapore-postgres.render.com/trackpoint_postgresql
      - key: JWT_SECRET
        generateValue: true
